rewriting umount tests
For readability and adding a debug trace

diff --git a/usbmount b/usbmount
--- a/usbmount
+++ b/usbmount
@@ -247,22 +247,25 @@ elif [ "$1" = remove ]; then
 		if [ -z $MOUNTPOINTS ]; then
 			# Default mountpoints
 			if expr "$mountpoint " : '/media/usb[0-9] ' ;then
-				if in_list "$fstype" "$FILESYSTEMS"; then
-					log debug "filesystem type $fstype"
-					log info "exec: umount -l $mountpoint"
-					umount -l "$mountpoint" || log err "the umount command failed ($?)"
-				fi
+				managed_mountpoint="true"
 			fi
 		else
 			# From config file
 			if in_list "$mountpoint" "$MOUNTPOINTS" ;then
-				if in_list "$fstype" "$FILESYSTEMS"; then
-					log debug "filesystem type $fstype"
-					log info "exec: umount -l $mountpoint"
-					umount -l "$mountpoint" || log err "the umount command failed ($?)"
-				fi
+				managed_mountpoint="true"
 			fi
 		fi
+		if [ "$managed_mountpoint" = "true" ]; then
+			if in_list "$fstype" "$FILESYSTEMS"; then
+				log info "exec: umount -l $mountpoint"
+				umount -l "$mountpoint" || log err "the umount command failed ($?)"
+			else
+				log debug "filesystem $fstype is not maintained by usbmout"
+			fi
+		else
+			log debug "mountpoint $mountpoint is not maintained by usbmout"
+		fi
+
 	else
 		log info "non-mounted device"
 	fi
